language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-RC2

jdk:
  - oraclejdk8

# push onto the new gce infra on travis
sudo: required

script:
  - sbt -J-Xss6M -J-Xmx4G ++$TRAVIS_SCALA_VERSION validate

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
